// Copyright (C) 2024 Hathor Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

/**
 * ClockSync.hpp — worker/master clock mapping, offset measurement, and drift
 * detection for B4-K6.
 *
 * Per Decision #15: sample/frame timestamps are generated by the Phase-1
 * scheduler (Tidal/Hathor) before IPC transport. The worker receives these
 * absolute sample timestamps and must map them to its own sample timeline
 * to execute them at the correct position.
 *
 * Per Decision #17: clock offset is measured via ping/pong timestamp
 * exchange over the control socket — this is the worker measuring the delta
 * between its local sample clock and the master's sample clock.
 *
 * Per Decision #16: if the measured offset is outside tolerance, the worker
 * enters "drift recovery" — it adjusts the offset linearly over a configurable
 * window rather than snapping, to avoid audible glitches.
 *
 * Per Decision #18: the offset is maintained atomically so the audio callback
 * can read it lock-free. The full timing records are logged off-thread.
 *
 * Requirement: B4-K6 clock synchronization
 */

#include <atomic>
#include <cstdint>
#include <cstdio>
#include <cmath>
#include <chrono>

namespace hathor {

class ClockSync {
public:
    static constexpr double kDefaultDriftToleranceMs = 0.5; ///< max drift before recovery (0.5ms = ~22 samples @44.1kHz)
    static constexpr double kDefaultMaxOffsetMs = 50.0;     ///< max acceptable offset (beyond this = restart)

    explicit ClockSync(double driftToleranceMs = kDefaultDriftToleranceMs,
                       double maxOffsetMs = kDefaultMaxOffsetMs)
        : m_masterSampleRate(44100.0)
        , m_localSampleRate(44100.0)
        , m_measuredOffsetSamples(0.0)
        , m_driftRate(0.0)
        , m_lastOffsetMeasurement(0)
        , m_driftToleranceMs(driftToleranceMs)
        , m_maxOffsetMs(maxOffsetMs)
        , m_lastRecoveryTarget(0)
        , m_recoveryStart(0)
        , m_recoveryStartOffset(0.0)
    {}

    void setSampleRates(double masterSampleRate, double localSampleRate) {
        m_masterSampleRate = masterSampleRate;
        m_localSampleRate  = localSampleRate;
    }

    void updateOffset(uint64_t masterSampleTs, uint64_t localSampleTs, uint64_t roundTripMicros) {
        const double rttSamples = (static_cast<double>(roundTripMicros) / 1e6) * m_masterSampleRate * 0.5;
        double newOffset = static_cast<double>(localSampleTs) - static_cast<double>(masterSampleTs) - rttSamples;

        if (m_lastOffsetMeasurement == 0) {
            m_measuredOffsetSamples.store(newOffset, std::memory_order_release);
            m_driftRate.store(0.0, std::memory_order_release);
        } else {
            const uint64_t samplesElapsed = localSampleTs - m_lastLocalSample;
            if (samplesElapsed > 0) {
                const double prevOffset = m_measuredOffsetSamples.load(std::memory_order_acquire);
                const double deltaOffset = newOffset - prevOffset;
                const double localDriftRate = deltaOffset / static_cast<double>(samplesElapsed);
                m_measuredOffsetSamples.store(newOffset, std::memory_order_release);
                m_driftRate.store(localDriftRate, std::memory_order_release);
            }
        }

        m_lastOffsetMeasurement = localSampleTs;
        m_lastLocalSample = localSampleTs;

        const double offsetMs = (newOffset / m_masterSampleRate) * 1000.0;
        if (std::abs(offsetMs) > m_driftToleranceMs) {
            initiateRecovery(localSampleTs, newOffset);
        }
    }

    uint64_t masterToLocal(uint64_t masterSampleTs) const noexcept {
        const double offset = m_measuredOffsetSamples.load(std::memory_order_acquire);
        return static_cast<uint64_t>(static_cast<double>(masterSampleTs) - offset);
    }

    double getOffsetMs() const noexcept {
        const double offset = m_measuredOffsetSamples.load(std::memory_order_acquire);
        return (offset / m_masterSampleRate) * 1000.0;
    }

    bool isWithinTolerance() const noexcept {
        return std::abs(getOffsetMs()) <= m_driftToleranceMs;
    }

    bool needsRestart() const noexcept {
        return std::abs(getOffsetMs()) > m_maxOffsetMs;
    }

    double getDriftRate() const noexcept {
        return m_driftRate.load(std::memory_order_acquire);
    }

private:
    void initiateRecovery(uint64_t localSampleTs, double currentOffset) {
        const double recoveryWindow = std::abs(currentOffset) * 10.0;
        m_lastRecoveryTarget.store(localSampleTs + static_cast<uint64_t>(recoveryWindow),
                                   std::memory_order_release);
        m_recoveryStart.store(localSampleTs, std::memory_order_release);
        m_recoveryStartOffset.store(currentOffset, std::memory_order_release);
        std::printf("[ClockSync] Drift recovery: offset=%.3fms\n",
                    (currentOffset / m_masterSampleRate) * 1000.0);
    }

    double m_masterSampleRate;
    double m_localSampleRate;

    alignas(64) std::atomic<double> m_measuredOffsetSamples;
    alignas(64) std::atomic<double> m_driftRate;
    alignas(64) std::atomic<uint64_t> m_lastOffsetMeasurement;
    uint64_t m_lastLocalSample = 0;

    double m_driftToleranceMs;
    double m_maxOffsetMs;

    alignas(64) std::atomic<uint64_t> m_lastRecoveryTarget;
    alignas(64) std::atomic<uint64_t> m_recoveryStart;
    alignas(64) std::atomic<double> m_recoveryStartOffset;
};

} // namespace hathor