// Copyright (C) 2024 Hathor Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

/**
 * EventTransport.hpp — shared-memory event transport for B4-K6.
 *
 * Extends the B4-K0.6 shared-memory transport contract with a lock-free SPSC
 * ring of MusicalEvent structs. The main process (AudioEngine, on the audio
 * thread or a near-RT thread) is the producer; the worker process is the
 * consumer.
 *
 * Per Decision #22: events carry an authoritative sample-frame timestamp
 * generated by the Phase-1 scheduler (Tidal/Hathor master clock) BEFORE IPC
 * transport. The worker schedules events by this timestamp, not by IPC arrival.
 *
 * Per Decision #23: the event ring is a separate data plane from the control
 * socket. The control socket remains for lifecycle commands; events flow
 * through shared memory. This header defines the shared-memory layout only.
 *
 * The event ring is a power-of-two SPSC ring (reusing the SpscSampleRing
 * pattern from B4-K1, adapted for MusicalEvent objects). Each slot carries
 * an event + seqlock sequence counter for cross-process validation.
 *
 * Layout:
 *   SharedEventTransport {
 *     magic           — sanity check (0xB4E7V3NT)
 *     generation      — worker session identity (must match SharedAudioTransport)
 *     writeSeq        — producer write counter (atomic)
 *     readSeq         — consumer read counter (atomic)
 *     sampleRate      — master sample rate (for timestamp reference)
 *     eventCount      — total events written (atomic, diagnostic)
 *     droppedCount    — events dropped due to ring full (atomic, diagnostic)
 *     slots[EVENT_RING_CAPACITY] — the SPSC ring
 *   }
 *
 * Seqlock discipline for EventSlot:
 *   Writer: seq.store(wSeq | 1, release);  // odd = in-progress
 *           ... copy event into slot ...
 *           seq.store(wSeq + 2, release);  // even = complete
 *
 *   Reader: s0 = seq.load(acquire);
 *           if (s0 & 1) -> discard (write in progress)
 *           copy event from slot
 *           s1 = seq.load(acquire);
 *           if (s1 != s0) -> discard (torn read)
 *
 * Requirement: B4-K6 (event transport), reuses B4-K1 SPSC pattern + B4-K0.6 seqlock
 */

#include "MusicalEvent.hpp"

#include <atomic>
#include <cstdint>
#include <cstring>

namespace hathor::audio_worker {

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Magic value for the event transport header (0xB4E7V3NT in hex).
constexpr uint32_t kEventMagic = 0xB4E70306u;

/// Capacity of the event ring (power of two for bitmask indexing).
/// Chosen to hold ~1 second of 64-sample audio blocks at peak event density.
constexpr uint32_t kEventRingCapacity = 4096;
constexpr uint32_t kEventRingMask     = kEventRingCapacity - 1;

static_assert((kEventRingCapacity & kEventRingMask) == 0,
              "kEventRingCapacity must be a power of two");

// ---------------------------------------------------------------------------
// EventSlot — one slot in the event ring (seqlock-protected)
// ---------------------------------------------------------------------------

struct EventSlot {
    /// Aligned to cache line to reduce false sharing between producer and
    /// consumer. MusicalEvent is ~64+ bytes, so the alignas(64) on the
    /// sequence counter ensures it sits on a fresh cache line.
    alignas(64) MusicalEvent event;

    /// Seqlock sequence counter.
    /// Even = complete/idle; Odd = write in progress.
    /// Writer increments by 2 per completed event.
    std::atomic<uint64_t> seq{0};
};

// ---------------------------------------------------------------------------
// SharedEventTransport — the shared-memory event ring header
// ---------------------------------------------------------------------------

struct SharedEventTransport {
    // -- Identification --
    std::atomic<uint32_t> magic{kEventMagic};
    std::atomic<uint64_t> generation{0};

    // -- Producer/consumer coordination --
    std::atomic<uint64_t> writeSeq{0};     ///< producer publish counter
    std::atomic<uint64_t> readSeq{0};      ///< consumer consume counter

    // -- Audio format reference --
    std::atomic<uint32_t> sampleRate{44100};

    // -- Diagnostics (best-effort, producer side) --
    std::atomic<uint64_t> eventCount{0};     ///< total events enqueued
    std::atomic<uint64_t> droppedCount{0};   ///< events dropped (ring full)

    // -- The ring buffer of event slots --
    EventSlot slots[kEventRingCapacity];

    // -- Compile-time size info --
    static constexpr size_t ringCapacity() { return kEventRingCapacity; }
};

/// Total size of the event transport shared-memory segment.
inline constexpr size_t kEventShmSize = sizeof(SharedEventTransport);

} // namespace hathor::audio_worker
