// Copyright (C) 2024 Hathor Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

/**
  * GhostProtocol.hpp — JUCE-free protocol types for llm-ls integration.
  *
  * llm-ls (v0.5.3) is a Rust-based LSP server for LLM-powered code completion.
  * It implements the custom LSP method `llm-ls/getCompletions` (NOT the
  * standard `textDocument/completion`). The request sends FIM (Fill-in-the-Middle)
  * context: prefix, suffix, and middle marker. The response returns an array
  * of completion strings.
  *
  * AI-G2 (Fill-in-the-Middle as a First-Class Ghost-Writing Requirement):
  *   The completion request explicitly preserves both prefix and suffix.
  *   The document text before the cursor (prefix) and after the cursor
  *   (suffix) are computed and stored in `docPrefix`/`docSuffix` on every
  *   request. The generated completion is trimmed against the suffix so
  *   only the MIDDLE (the missing code between prefix and suffix) is
  *   inserted at the cursor. The suffix is never silently discarded.
  *
  * These structs mirror the subset of llm-ls message types that Hathor's
  * ghost-text integration needs. All types are plain C++ with no JUCE
  * dependencies, so the GhostCompletionLogic that consumes them is fully
  * unit-testable in hathor-ui-tests.
  *
  * FIM contract:
  *   PREFIX   = document text before cursor (stored in docPrefix)
  *   SUFFIX   = document text after cursor (stored in docSuffix)
  *   MIDDLE   = generated by the LLM, trimmed against prefix/suffix
  *   The editor inserts only the MIDDLE at the cursor location.
  *
  * Architecture (Hathor ghost text):
  *
 *   HathorTab → GhostLlmClient (JUCE, process mgmt) → LspMessageFramer
 *                                      → GhostJsonRpc (JUCE-free serialization)
 *                                      → GhostCompletionLogic (JUCE-free, tested)
 *                                      → GhostTextOverlay (JUCE, rendering)
  *
  * Requirement references: AI-2, AI-3, AI-4, AI-8, AI-G2
  */

#include <nlohmann/json.hpp>

#include <string>
#include <vector>

namespace hathor::lsp {

// ---------------------------------------------------------------------------
// GhostContext — current editor state snapshot for ghost text
// ---------------------------------------------------------------------------

/**
  * A point-in-time snapshot of the editor state needed for ghost-text requests.
  * This mirrors the fields from EditorContextSnapshot relevant to FIM.
  *
  * AI-G2: includes explicit docPrefix/docSuffix for FIM trimming.
  * AI-8: includes authoringContext (dynamic authoring context JSON,
  *       assembled by AuthoringContext — may be null if not wired).
  *
  * Moved here from GhostCompletionLogic.hpp so that GhostTriggerPolicy.hpp
  * (which includes GhostProtocol.hpp) can reference it without creating
  * a circular include dependency.
  */
struct GhostContext {
    std::string documentText;  ///< full document text
    std::string uri;           ///< file:// URI or synthetic URI
    std::string languageId;    ///< "hathor" or "chuck"
    int         line      = 0; ///< 0-based cursor line
    int         character = 0; ///< 0-based cursor character offset
    int         revision  = 0; ///< incremented on each document edit

    // AI-G8: Dynamic authoring context (from AuthoringContext / AI-8).
    // May be null if the AI-8 context provider is not wired. When present,
    // this JSON includes supported-surface info (AI-3), diagnostics, editor
    // state, and other relevant project/language information.
    nlohmann::json authoringContext;
};

// ---------------------------------------------------------------------------
// llm-ls backend type
// ---------------------------------------------------------------------------

/**
 * The LLM backend used by llm-ls.
 * Maps to the Rust `Backend` enum in llm-ls, which serializes as
 * lowercase via `#[serde(rename_all = "lowercase", tag = "backend")]`.
 */
enum class LlmBackend {
    HuggingFace,  ///< serialized as "huggingface"
    LlamaCpp,     ///< serialized as "llamacpp"
    Ollama,        ///< serialized as "ollama"
    OpenAi,       ///< serialized as "openai"
    Tgi,          ///< serialized as "tgi"
};

/**
 * Serialize a backend to its llm-ls string representation.
 * Must be lowercase to match llm-ls's `#[serde(rename_all = "lowercase")]`.
 */
inline std::string backendToString(LlmBackend b)
{
    switch (b)
    {
        case LlmBackend::HuggingFace: return "huggingface";
        case LlmBackend::LlamaCpp:    return "llamacpp";
        case LlmBackend::Ollama:      return "ollama";
        case LlmBackend::OpenAi:      return "openai";
        case LlmBackend::Tgi:         return "tgi";
    }
    return "huggingface";
}

// ---------------------------------------------------------------------------
// llm-ls completion request parameters
// ---------------------------------------------------------------------------

/**
  * FIM (Fill-in-the-Middle) additional-context parameters for llm-ls.
  *
  * When fim.enabled is true, llm-ls constructs a FIM prompt from:
  *   - The document prefix (text before cursor, extracted from the synced
  *     document via didOpen/didChange)
  *   - The document suffix (text after cursor, extracted from the synced
  *     document)
  *   - fim.prefix: ADDITIONAL context prepended to the prompt (before the
  *     document prefix). Used for AI-8 authoring context, supported-surface
  *     info, and completion instructions.
  *   - fim.suffix: ADDITIONAL context inserted between the document prefix
  *     and document suffix.
  *   - fim.middle: the FIM middle marker token (model-specific, usually
  *     "<fim-middle>"). Left empty; llm-ls fills from tokenizer.
  *
  * NOTE: The document prefix/suffix are NOT placed in fim.prefix/fim.suffix.
  * Those fields carry *additional* context only. The document text itself is
  * synced via didOpen/didChange and llm-ls extracts prefix/suffix internally.
  * The GhostCompletionRequest carries docPrefix/docSuffix separately for
  * client-side trimming and verification (AI-G2).
  */
struct FimParams {
    bool        enabled = false;
    std::string prefix;   ///< additional context prepended before document prefix
    std::string suffix;   ///< additional context inserted between doc prefix/suffix
    std::string middle;   ///< FIM middle marker (left empty; llm-ls fills from tokenizer)
};

/**
 * Backend configuration for the llm-ls request.
 *
 * Each request carries its own backend config so that:
 *   - Credentials are provided per-request (never stored in editor text)
 *   - The model can be selected at invocation time
 *   - The context window size is explicit
 */
struct BackendConfig {
    LlmBackend  backend     = LlmBackend::HuggingFace;
    std::string url;         ///< API endpoint URL (empty for HuggingFace default)
    std::string model;       ///< model identifier (e.g. "bigcode/starcoder")
};

/**
  * Parameters for a single `llm-ls/getCompletions` request.
  *
  * These map directly to the serde fields llm-ls v0.5.3 expects.
  * Field names use camelCase to match the Rust struct serialization.
  *
  * AI-G2 (Fill-in-the-Middle as a First-Class Requirement):
  *   - `docPrefix`/`docSuffix` carry the explicit document prefix/suffix
  *     (computed from cursor position). These are NOT sent to llm-ls
  *     directly (llm-ls extracts them from the synced document), but are
  *     used for client-side response trimming and result verification.
  *   - `authoringContext` carries the AI-8 dynamic authoring context
  *     (supported-surface from AI-3, editor state, diagnostics) as
  *     additional FIM context (serialized into fim.prefix).
  */
struct GhostCompletionRequest {
    // --- Document identity ---
    std::string uri;           ///< file:// URI or synthetic URI
    std::string languageId;    ///< "hathor" or "chuck"

    // --- Cursor position ---
    int line      = 0;         ///< 0-based line number
    int character = 0;         ///< 0-based character offset on the line

    // --- Text context ---
    std::string textDocument;  ///< full document text (synced via didOpen/didChange)

    // --- Explicit FIM document context (AI-G2) ---
    // These are the actual document prefix/suffix computed from the cursor
    // position. They are used for client-side response trimming: the generated
    // MIDDLE must fit between docPrefix and docSuffix without overlap.
    // NOT sent to llm-ls (which extracts them from the synced document).
    std::string docPrefix;     ///< text before cursor (from start of document to cursor)
    std::string docSuffix;     ///< text after cursor (from cursor to end of document)

    // --- FIM additional context (AI-8) ---
    // fim.prefix carries the AI-8 authoring context (supported surface,
    // instructions, etc.) as additional context prepended to the prompt.
    // fim.suffix and fim.middle are typically left empty.
    FimParams   fim;

    // --- AI-8 authoring context (JSON, for trimming/inspection) ---
    // The dynamic authoring context assembled by AuthoringContext (AI-8),
    // including AI-3 supported-surface info. Serialized into fim.prefix.
    nlohmann::json authoringContext;

    // --- Backend ---
    BackendConfig backend;

    // --- Request-level credentials (env-var sourced, never persisted) ---
    std::string apiToken;      ///< bearer token (from HF_API_TOKEN / OPENAI_API_KEY)

    // --- Generation parameters ---
    std::string tokenizerConfig;  ///< tokenizer configuration path
    int         contextWindow    = 2048;  ///< max context window
    bool        tlsSkipVerify    = false;  ///< skip TLS verification (dev only)

    // --- Request body for custom backends ---
    // If non-empty, llm-ls sends this as the raw body instead of building
    // its own request from the standard fields.
    nlohmann::json requestBody;

    // --- Misc ---
    bool disableUrlPathCompletion = false;  ///< don't append URI path as suffix
    std::vector<std::string> tokensToClear;  ///< tokens to clear before completion

    // --- J-2: Number of candidate completions to request ---
    // If non-zero, the llm-ls request includes `n` so the server returns
    // up to `maxCandidates` independent completion candidates. The client
    // caches all returned candidates and lets the user cycle through them
    // locally without re-requesting.
    uint32_t maxCandidates = 0;  ///< 0 = server default; otherwise bounded N

    /** Serialize this request into the nlohmann::json params for llm-ls. */
    nlohmann::json toJson() const;
};

// ---------------------------------------------------------------------------
// llm-ls completion response
// ---------------------------------------------------------------------------

/**
 * A single completion result from llm-ls.
 *
 * llm-ls returns completions as an array of objects, each with a
 * "generated_text" field containing the LLM's output text.
 */
struct GhostCompletion {
    std::string generatedText;
};

/**
 * The full response from a `llm-ls/getCompletions` request.
 *
 * llm-ls responses include a `request_id` (UUID) that we use to correlate
 * the response with our pending request. Since llm-ls does not support
 * `$/cancelRequest`, we track staleness via revision counters in
 * GhostCompletionLogic.
 */
struct GhostCompletionResponse {
    std::string request_id;
    std::vector<GhostCompletion> completions;
};

/**
 * Parse an llm-ls completion response JSON into a typed struct.
 * Returns std::nullopt if parsing fails.
 */
std::optional<GhostCompletionResponse> parseGhostCompletionResponse(
    const nlohmann::json& j);

// ---------------------------------------------------------------------------
// llm-ls notification types (accept/reject)
// ---------------------------------------------------------------------------

struct AcceptCompletionParams {
    std::string requestId;       ///< the request_id from the completion response (UUID string)
    uint32_t    acceptedCompletion = 0;  ///< index of the accepted completion
    std::vector<uint32_t> shownCompletions;  ///< indices of completions shown to user
};

/**
 * Parameters for the `llm-ls/rejectCompletion` notification.
 * Sent when the user dismisses or modifies a ghost completion suggestion.
 *
 * Verified against llm-ls source: the Rust `RejectCompletionParams` struct
 * has `request_id: Uuid` and `shown_completions: Vec<u32>`.
 */
struct RejectCompletionParams {
    std::string requestId;       ///< the request_id from the completion response (UUID string)
    std::vector<uint32_t> shownCompletions;  ///< indices of completions shown to user
};

// ---------------------------------------------------------------------------
// Ghost completion result — consumed by the JUCE overlay
// ---------------------------------------------------------------------------

/**
  * The final ghost text to display, after processing by GhostCompletionLogic.
  *
  * The `text` field is the completion text to show as ghost/inlay text
  * starting from the cursor position. If `displayText` differs from `insertText`,
  * it should be shown to the user while `insertText` is what gets inserted.
  *
  * AI-G2 (Fill-in-the-Middle): `docPrefix` and `docSuffix` carry the
  * document context the MIDDLE was generated for. The editor can verify
  * that the ghost text still fits between these before displaying or
  * inserting it.
  */
struct GhostResult {
    std::string text;           ///< the MIDDLE text to insert at cursor (trimmed)
    std::string displayText;    ///< text to show in the overlay (may include hints)
    std::string insertText;     ///< text to insert on accept
    std::string requestId;      ///< for accept/reject notifications

    // --- AI-G2: Explicit FIM document context (for verification) ---
    std::string docPrefix;      ///< document prefix this completion was generated for
    std::string docSuffix;     ///< document suffix this completion was generated for

    int         cursorLine = 0;  ///< 0-based line where ghost was requested
    int         character  = 0;  ///< 0-based character offset on the line

    /// Index of this candidate within the original response's completions array.
    /// Used when sending the accept/reject notification back to llm-ls so the
    /// server knows which candidate was accepted.  Defaults to 0 for backward
    /// compatibility with single-candidate responses.
    uint32_t    candidateIndex = 0;

    bool        isEmpty() const noexcept { return text.empty(); }
};

/**
  * Result of a partial acceptance of a ghost completion.
  *
  * When the user accepts only a prefix of the displayed ghost text (J-3),
  * the accepted prefix is returned for document insertion, and the remaining
  * suffix is returned as an updated GhostResult whose docPrefix has been
  * extended to include the accepted text. The caller (HathorTab) is
  * responsible for inserting the accepted text into the document via the
  * normal CodeDocument edit mechanism (which creates a proper undo entry),
  * and for re-displaying the remaining suffix via the overlay.
  *
  * AI-G6 (Ghost Text Is UI State): the remaining suffix has NOT entered the
  * document or undo history — it remains ghost overlay state until explicitly
  * accepted or dismissed.
  */
struct PartialAcceptResult {
    std::string   acceptedText;      ///< the prefix that was accepted (for document insertion)
    GhostResult   remainingResult;   ///< updated result for the remaining suffix (for display)
};

} // namespace hathor::lsp