// Copyright (C) 2024 Hathor Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

/**
 * HathorLookAndFeel.cpp — implementation of the central design-system
 * LookAndFeel subclass.
 *
 * This file is the single source of truth for:
 *   - All JUCE colour-ID defaults (setColour calls)
 *   - JetBrains Mono font loading (4 weights, embedded as BinaryData)
 *   - Custom button / slider / scrollbar drawing
 *   - Font-family substitution (getTypefaceForFont override)
 */

#include "HathorLookAndFeel.hpp"

// juce_gui_extra is needed for juce::CodeEditorComponent colour IDs.
#include <juce_gui_extra/juce_gui_extra.h>

// Generated by juce_add_binary_data (hathor_font_data target)
#include "BinaryData.h"

// ===========================================================================
// Embedded JetBrains Mono typeface accessors
// ===========================================================================

juce::Typeface::Ptr HathorLookAndFeel::regularTypeface()
{
    static juce::Typeface::Ptr tf = juce::Typeface::createSystemTypefaceFor(
        BinaryData::JetBrainsMonoRegular_ttf,
        static_cast<size_t>(BinaryData::JetBrainsMonoRegular_ttfSize));
    return tf;
}

juce::Typeface::Ptr HathorLookAndFeel::mediumTypeface()
{
    static juce::Typeface::Ptr tf = juce::Typeface::createSystemTypefaceFor(
        BinaryData::JetBrainsMonoMedium_ttf,
        static_cast<size_t>(BinaryData::JetBrainsMonoMedium_ttfSize));
    return tf;
}

juce::Typeface::Ptr HathorLookAndFeel::semiBoldTypeface()
{
    static juce::Typeface::Ptr tf = juce::Typeface::createSystemTypefaceFor(
        BinaryData::JetBrainsMonoSemiBold_ttf,
        static_cast<size_t>(BinaryData::JetBrainsMonoSemiBold_ttfSize));
    return tf;
}

juce::Typeface::Ptr HathorLookAndFeel::boldTypeface()
{
    static juce::Typeface::Ptr tf = juce::Typeface::createSystemTypefaceFor(
        BinaryData::JetBrainsMonoBold_ttf,
        static_cast<size_t>(BinaryData::JetBrainsMonoBold_ttfSize));
    return tf;
}

// ===========================================================================
// Static font factory methods
// ===========================================================================

juce::Font HathorLookAndFeel::fontRegular(float height) noexcept
{
    return juce::Font(juce::FontOptions{}.withHeight(height).withTypeface(regularTypeface()));
}

juce::Font HathorLookAndFeel::fontMedium(float height) noexcept
{
    return juce::Font(juce::FontOptions{}.withHeight(height).withTypeface(mediumTypeface()));
}

juce::Font HathorLookAndFeel::fontSemiBold(float height) noexcept
{
    return juce::Font(juce::FontOptions{}.withHeight(height).withTypeface(semiBoldTypeface()));
}

juce::Font HathorLookAndFeel::fontBold(float height) noexcept
{
    return juce::Font(juce::FontOptions{}.withHeight(height).withTypeface(boldTypeface()));
}

// ===========================================================================
// Constructor — sets every JUCE colour ID from design tokens
// ===========================================================================

HathorLookAndFeel::HathorLookAndFeel()
{
    using C = HathorLookAndFeel::Colours;

    // -----------------------------------------------------------------------
    // Window / component backgrounds
    // -----------------------------------------------------------------------
    setColour(juce::ResizableWindow::backgroundColourId,  juce::Colour(C::background));
    setColour(juce::DocumentWindow::backgroundColourId,   juce::Colour(C::background));

    // -----------------------------------------------------------------------
    // Generic component / label text
    // -----------------------------------------------------------------------
    setColour(juce::Label::textColourId,       juce::Colour(C::textPrimary));
    setColour(juce::Label::backgroundColourId, juce::Colour(C::background));

    // -----------------------------------------------------------------------
    // TextEditor (chat input, search bar, etc.)
    // -----------------------------------------------------------------------
    setColour(juce::TextEditor::backgroundColourId,    juce::Colour(C::surfaceHigh));
    setColour(juce::TextEditor::textColourId,          juce::Colour(C::textPrimary));
    setColour(juce::TextEditor::outlineColourId,       juce::Colour(C::surfaceHighest));
    setColour(juce::TextEditor::focusedOutlineColourId, juce::Colour(C::accent));
    setColour(juce::TextEditor::highlightColourId,     juce::Colour(C::accent).withAlpha(0.4f));
    setColour(juce::TextEditor::highlightedTextColourId, juce::Colour(C::background));
    setColour(juce::CaretComponent::caretColourId,     juce::Colour(C::accent));

    // -----------------------------------------------------------------------
    // ListBox / TreeView (Explorer panel)
    // -----------------------------------------------------------------------
    setColour(juce::ListBox::backgroundColourId,  juce::Colour(C::background));
    setColour(juce::ListBox::outlineColourId,     juce::Colours::transparentBlack);

    setColour(juce::TreeView::backgroundColourId,             juce::Colour(C::background));
    setColour(juce::TreeView::linesColourId,                   juce::Colour(C::surfaceHighest));
    setColour(juce::TreeView::selectedItemBackgroundColourId, juce::Colour(C::surfaceLow));

    // -----------------------------------------------------------------------
    // CodeEditorComponent
    // -----------------------------------------------------------------------
    setColour(juce::CodeEditorComponent::backgroundColourId,  juce::Colour(C::surface));
    setColour(juce::CodeEditorComponent::defaultTextColourId, juce::Colour(C::codeText));
    setColour(juce::CodeEditorComponent::highlightColourId,   juce::Colour(C::accent).withAlpha(0.3f));
    setColour(juce::CodeEditorComponent::lineNumberBackgroundId, juce::Colour(C::surfaceLow));
    setColour(juce::CodeEditorComponent::lineNumberTextId,    juce::Colour(C::codeLineNum));

    // -----------------------------------------------------------------------
    // TabbedComponent / TabbedButtonBar
    // -----------------------------------------------------------------------
    setColour(juce::TabbedComponent::backgroundColourId,  juce::Colour(C::background));
    setColour(juce::TabbedComponent::outlineColourId,    juce::Colour(C::surfaceHighest));
    setColour(juce::TabbedButtonBar::tabTextColourId,    juce::Colour(C::textSecondary));
    setColour(juce::TabbedButtonBar::tabOutlineColourId, juce::Colour(C::surfaceHighest));
    setColour(juce::TabbedButtonBar::frontTextColourId, juce::Colour(C::textPrimary));

    // -----------------------------------------------------------------------
    // ScrollBar
    // -----------------------------------------------------------------------
    setColour(juce::ScrollBar::backgroundColourId, juce::Colours::transparentBlack);
    setColour(juce::ScrollBar::thumbColourId,      juce::Colour(C::surfaceHighest));
    setColour(juce::ScrollBar::trackColourId,      juce::Colour(C::background));

    // -----------------------------------------------------------------------
    // Slider
    // -----------------------------------------------------------------------
    setColour(juce::Slider::backgroundColourId,          juce::Colour(C::surfaceHigh));
    setColour(juce::Slider::thumbColourId,               juce::Colour(C::textPrimary));
    setColour(juce::Slider::trackColourId,               juce::Colour(C::surfaceHighest));
    setColour(juce::Slider::rotarySliderFillColourId,    juce::Colour(C::accent));
    setColour(juce::Slider::rotarySliderOutlineColourId, juce::Colour(C::surfaceHighest));
    setColour(juce::Slider::textBoxTextColourId,        juce::Colour(C::textPrimary));
    setColour(juce::Slider::textBoxBackgroundColourId,  juce::Colour(C::surfaceHigh));
    setColour(juce::Slider::textBoxOutlineColourId,     juce::Colour(C::surfaceHighest));
    setColour(juce::Slider::textBoxHighlightColourId,   juce::Colour(C::accent).withAlpha(0.4f));

    // -----------------------------------------------------------------------
    // ComboBox
    // -----------------------------------------------------------------------
    setColour(juce::ComboBox::backgroundColourId, juce::Colour(C::surfaceHigh));
    setColour(juce::ComboBox::textColourId,     juce::Colour(C::textPrimary));
    setColour(juce::ComboBox::outlineColourId,  juce::Colour(C::surfaceHighest));
    setColour(juce::ComboBox::buttonColourId,   juce::Colour(C::surfaceHigh));
    setColour(juce::ComboBox::arrowColourId,    juce::Colour(C::textPrimary));

    // -----------------------------------------------------------------------
    // PopupMenu
    // -----------------------------------------------------------------------
    setColour(juce::PopupMenu::backgroundColourId,             juce::Colour(C::surfaceContainer));
    setColour(juce::PopupMenu::textColourId,                   juce::Colour(C::textPrimary));
    setColour(juce::PopupMenu::highlightedBackgroundColourId,  juce::Colour(C::accent).withAlpha(0.3f));
    setColour(juce::PopupMenu::highlightedTextColourId,        juce::Colour(C::background));
    setColour(juce::PopupMenu::headerTextColourId,             juce::Colour(C::textMuted));

    // -----------------------------------------------------------------------
    // AlertWindow / DialogWindow
    // -----------------------------------------------------------------------
    setColour(juce::AlertWindow::backgroundColourId,  juce::Colour(C::surfaceContainer));
    setColour(juce::AlertWindow::textColourId,        juce::Colour(C::textPrimary));
    setColour(juce::AlertWindow::outlineColourId,     juce::Colour(C::surfaceHighest));

    setColour(juce::DialogWindow::backgroundColourId, juce::Colour(C::surfaceContainer));
    setColour(juce::DialogWindow::textColourId,       juce::Colour(C::textPrimary));

    // -----------------------------------------------------------------------
    // TextButton
    // -----------------------------------------------------------------------
    setColour(juce::TextButton::buttonColourId,   juce::Colour(C::surfaceHigh));
    setColour(juce::TextButton::buttonOnColourId, juce::Colour(C::accent));
    setColour(juce::TextButton::textColourOffId,  juce::Colour(C::textPrimary));
    setColour(juce::TextButton::textColourOnId,   juce::Colour(C::background));

    // -----------------------------------------------------------------------
    // TooltipWindow
    // -----------------------------------------------------------------------
    setColour(juce::TooltipWindow::backgroundColourId, juce::Colour(C::surfaceContainer));
    setColour(juce::TooltipWindow::textColourId,       juce::Colour(C::textPrimary));
    setColour(juce::TooltipWindow::outlineColourId,    juce::Colour(C::surfaceHighest));

    // -----------------------------------------------------------------------
    // PropertyComponent / PropertyPanel
    // -----------------------------------------------------------------------
    setColour(juce::PropertyComponent::backgroundColourId, juce::Colour(C::background));
    setColour(juce::PropertyComponent::labelTextColourId,  juce::Colour(C::textSecondary));
}

// ===========================================================================
// Font family substitution — intercept all default-font requests
// ===========================================================================

juce::Typeface::Ptr HathorLookAndFeel::getTypefaceForFont(const juce::Font& font)
{
    const juce::String family = font.getTypefaceName().trim();

    // Intercept requests for:
    //   - No specific family (empty / system default sans-serif)
    //   - The system default monospaced font (e.g. Menlo, Monaco)
    //   - Explicit "JetBrains Mono" requests
    if (family.isEmpty()
        || family == juce::Font::getDefaultSansSerifFontName()
        || family == juce::Font::getDefaultMonospacedFontName()
        || family.containsIgnoreCase("jetbrains"))
    {
        const int styleFlags = font.getStyleFlags();

        if ((styleFlags & juce::Font::bold) != 0)
            return boldTypeface();

        return regularTypeface();
    }

    // For any other family, fall through to the base class.
    return juce::LookAndFeel_V4::getTypefaceForFont(font);
}

// ===========================================================================
// getTextButtonFont — JetBrains Mono Bold for text buttons
// ===========================================================================

juce::Font HathorLookAndFeel::getTextButtonFont(juce::TextButton& /*button*/,
                                                 int buttonHeight)
{
    // Use Medium weight at ~55% of button height for label-sized text.
    const float h = static_cast<float>(buttonHeight) * 0.55f;
    return HathorLookAndFeel::fontMedium(juce::jmax(h, 10.0f));
}

// ===========================================================================
// drawButtonBackground — dark theme button with green accent
// ===========================================================================

void HathorLookAndFeel::drawButtonBackground(juce::Graphics& g,
                                              juce::Button& button,
                                              const juce::Colour& /*backgroundColour*/,
                                              bool shouldDrawButtonAsHighlighted,
                                              bool shouldDrawButtonAsDown)
{
    using C = HathorLookAndFeel::Colours;

    const juce::Rectangle<float> bounds = button.getLocalBounds().toFloat();

    juce::Colour bg;

    if (button.getToggleState())
        bg = juce::Colour(C::accent);                       // active = green
    else if (shouldDrawButtonAsDown)
        bg = juce::Colour(C::surfaceContainer);             // pressed = slightly lighter
    else if (shouldDrawButtonAsHighlighted)
        bg = juce::Colour(C::surfaceLow);                   // hover = subtle tint
    else
        bg = juce::Colour(C::surfaceHigh);                  // default

    g.setColour(bg);
    g.fillRoundedRectangle(bounds, HathorLookAndFeel::Radius::small);
}

// ===========================================================================
// drawButtonText — green on active, primary text on inactive
// ===========================================================================

void HathorLookAndFeel::drawButtonText(juce::Graphics& g,
                                      juce::TextButton& button,
                                      bool shouldDrawButtonAsHighlighted,
                                      bool shouldDrawButtonAsDown)
{
    using C = HathorLookAndFeel::Colours;

    juce::Colour textCol = juce::Colour(C::textPrimary);

    if (button.getToggleState())
        textCol = juce::Colour(C::background); // green bg + dark text when on

    // Get the button's font via the LookAndFeel hook (JetBrains Mono).
    juce::Font font = getTextButtonFont(button, button.getHeight());

    if (shouldDrawButtonAsHighlighted || shouldDrawButtonAsDown)
        font = HathorLookAndFeel::fontBold(font.getHeight());
    else
        font = HathorLookAndFeel::fontRegular(font.getHeight());

    g.setColour(textCol);
    g.setFont(font);

    const juce::Rectangle<int> bounds = button.getLocalBounds();
    g.drawFittedText(button.getButtonText(), bounds,
                     juce::Justification::centred, 1, 1.0f);
}

// ===========================================================================
// drawLinearSlider — pill-track aesthetic from the mockup
// ===========================================================================

void HathorLookAndFeel::drawLinearSlider(juce::Graphics& g,
                                          int x, int y, int width, int height,
                                          float sliderPos,
                                          float /*minSliderPos*/, float /*maxSliderPos*/,
                                          juce::Slider::SliderStyle /*style*/,
                                          juce::Slider& /*slider*/)
{
    using C = HathorLookAndFeel::Colours;

    const bool isHorizontal = (width > height);
    const int  thumbSize    = isHorizontal ? 12 : 12;
    const float trackH       = isHorizontal ? 4.0f : static_cast<float>(width);

    const float trackY = y + (height - trackH) / 2.0f;
    juce::Rectangle<float> trackRect(x, trackY, width, trackH);

    // Track background (pill shape)
    g.setColour(juce::Colour(C::surfaceHighest));
    g.fillRoundedRectangle(trackRect, trackH / 2.0f);

    // Filled portion
    const float fillW = juce::jlimit(0.0f, static_cast<float>(width), sliderPos - x);
    if (fillW > 0)
    {
        juce::Rectangle<float> fillRect(x, trackY, fillW, trackH);
        g.setColour(juce::Colour(C::accent));
        g.fillRoundedRectangle(fillRect, trackH / 2.0f);
    }

    // Thumb (circle)
    const float thumbX = juce::jlimit(static_cast<float>(x),
                                      static_cast<float>(x + width),
                                      sliderPos);
    const float thumbY = y + height / 2.0f;
    g.setColour(juce::Colour(C::textPrimary));
    g.fillEllipse(thumbX - thumbSize / 2.0f,
                  thumbY - thumbSize / 2.0f,
                  thumbSize, thumbSize);
}

// ===========================================================================
// drawScrollbar — thin thumb, transparent track
// ===========================================================================

void HathorLookAndFeel::drawScrollbar(juce::Graphics& g,
                                       juce::ScrollBar& /*scrollbar*/,
                                       int x, int y, int width, int height,
                                       bool /*isScrollbarVertical*/,
                                       int /*thumbStartPosition*/, int /*thumbSize*/,
                                       bool /*isMouseOver*/, bool /*isMouseDown*/)
{
    using C = HathorLookAndFeel::Colours;

    // Track is transparent — let the parent background show through.
    // Thumb: dim, 8 px wide, 4 px corner radius (matches mockup).
    g.setColour(juce::Colour(C::surfaceHighest));

    juce::Rectangle<float> thumb(x, y, width, height);
    g.fillRoundedRectangle(thumb, HathorLookAndFeel::Radius::small);
}
