// Copyright (C) 2024 Hathor Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

/**
 * HathorLookAndFeel.cpp — implementation of the central design-system
 * LookAndFeel subclass.
 *
 * This file is the single source of truth for:
 *   - All JUCE colour-ID defaults (setColour calls)
 *   - JetBrains Mono font loading (4 weights, embedded as BinaryData)
 *   - Custom button / slider / scrollbar drawing
 *   - Font-family policy (getTypefaceForFont NOT overridden — Audit §1.2 I6)
 */

#include "HathorLookAndFeel.hpp"

// juce_gui_extra is needed for juce::CodeEditorComponent colour IDs.
#include <juce_gui_extra/juce_gui_extra.h>

// Generated by juce_add_binary_data (hathor_font_data target)
#include "BinaryData.h"

// ===========================================================================
// Embedded JetBrains Mono typeface accessors
// ===========================================================================

juce::Typeface::Ptr HathorLookAndFeel::regularTypeface()
{
    static juce::Typeface::Ptr tf = juce::Typeface::createSystemTypefaceFor(
        BinaryData::JetBrainsMonoRegular_ttf,
        static_cast<size_t>(BinaryData::JetBrainsMonoRegular_ttfSize));
    return tf;
}

juce::Typeface::Ptr HathorLookAndFeel::mediumTypeface()
{
    static juce::Typeface::Ptr tf = juce::Typeface::createSystemTypefaceFor(
        BinaryData::JetBrainsMonoMedium_ttf,
        static_cast<size_t>(BinaryData::JetBrainsMonoMedium_ttfSize));
    return tf;
}

juce::Typeface::Ptr HathorLookAndFeel::semiBoldTypeface()
{
    static juce::Typeface::Ptr tf = juce::Typeface::createSystemTypefaceFor(
        BinaryData::JetBrainsMonoSemiBold_ttf,
        static_cast<size_t>(BinaryData::JetBrainsMonoSemiBold_ttfSize));
    return tf;
}

juce::Typeface::Ptr HathorLookAndFeel::boldTypeface()
{
    static juce::Typeface::Ptr tf = juce::Typeface::createSystemTypefaceFor(
        BinaryData::JetBrainsMonoBold_ttf,
        static_cast<size_t>(BinaryData::JetBrainsMonoBold_ttfSize));
    return tf;
}

// ===========================================================================
// Embedded Inter typeface accessors — proportional UI font (OFL)
// ===========================================================================

juce::Typeface::Ptr HathorLookAndFeel::interRegularTypeface()
{
    static juce::Typeface::Ptr tf = juce::Typeface::createSystemTypefaceFor(
        BinaryData::InterRegular_ttf,
        static_cast<size_t>(BinaryData::InterRegular_ttfSize));
    return tf;
}

juce::Typeface::Ptr HathorLookAndFeel::interMediumTypeface()
{
    static juce::Typeface::Ptr tf = juce::Typeface::createSystemTypefaceFor(
        BinaryData::InterMedium_ttf,
        static_cast<size_t>(BinaryData::InterMedium_ttfSize));
    return tf;
}

juce::Typeface::Ptr HathorLookAndFeel::interSemiBoldTypeface()
{
    static juce::Typeface::Ptr tf = juce::Typeface::createSystemTypefaceFor(
        BinaryData::InterSemiBold_ttf,
        static_cast<size_t>(BinaryData::InterSemiBold_ttfSize));
    return tf;
}

juce::Typeface::Ptr HathorLookAndFeel::interBoldTypeface()
{
    static juce::Typeface::Ptr tf = juce::Typeface::createSystemTypefaceFor(
        BinaryData::InterBold_ttf,
        static_cast<size_t>(BinaryData::InterBold_ttfSize));
    return tf;
}

// ===========================================================================
// Static font factory methods
// ===========================================================================

juce::Font HathorLookAndFeel::fontRegular(float height) noexcept
{
    return juce::Font(juce::FontOptions{}.withHeight(height).withTypeface(regularTypeface()));
}

juce::Font HathorLookAndFeel::fontMedium(float height) noexcept
{
    return juce::Font(juce::FontOptions{}.withHeight(height).withTypeface(mediumTypeface()));
}

juce::Font HathorLookAndFeel::fontSemiBold(float height) noexcept
{
    return juce::Font(juce::FontOptions{}.withHeight(height).withTypeface(semiBoldTypeface()));
}

juce::Font HathorLookAndFeel::fontBold(float height) noexcept
{
    return juce::Font(juce::FontOptions{}.withHeight(height).withTypeface(boldTypeface()));
}

// ===========================================================================
// Inter UI font factory methods (proportional — OFL)
// ===========================================================================

juce::Font HathorLookAndFeel::uiFontRegular(float height) noexcept
{
    return juce::Font(juce::FontOptions{}.withHeight(height).withTypeface(interRegularTypeface()));
}

juce::Font HathorLookAndFeel::uiFontMedium(float height) noexcept
{
    return juce::Font(juce::FontOptions{}.withHeight(height).withTypeface(interMediumTypeface()));
}

juce::Font HathorLookAndFeel::uiFontSemiBold(float height) noexcept
{
    return juce::Font(juce::FontOptions{}.withHeight(height).withTypeface(interSemiBoldTypeface()));
}

juce::Font HathorLookAndFeel::uiFontBold(float height) noexcept
{
    return juce::Font(juce::FontOptions{}.withHeight(height).withTypeface(interBoldTypeface()));
}

// ===========================================================================
// getCodeFont / getUiFont — explicit font helpers (Audit §1.2 I6)
//
// Components should call these instead of relying on getTypefaceForFont
// interception.  getCodeFont() returns JetBrains Mono for code surfaces;
// getUiFont() returns Inter for proportional UI chrome.
// ===========================================================================

juce::Font HathorLookAndFeel::getCodeFont(float height) noexcept
{
    return fontRegular(height);
}

juce::Font HathorLookAndFeel::getCodeFont(float height, int styleFlags) noexcept
{
    if (styleFlags & juce::Font::bold)
        return fontBold(height);

    return juce::Font(juce::FontOptions{height, styleFlags}.withTypeface(regularTypeface()));
}

juce::Font HathorLookAndFeel::getUiFont(float height) noexcept
{
    return uiFontRegular(height);
}

juce::Font HathorLookAndFeel::getUiFont(float height, int styleFlags) noexcept
{
    if (styleFlags & juce::Font::bold)
        return uiFontBold(height);

    return juce::Font(juce::FontOptions{height, styleFlags}.withTypeface(interRegularTypeface()));
}

// ===========================================================================
// Palette — runtime design-token value-type (A1 design-token engine)
// ===========================================================================

// --- Design rationale: accent green --------------------------------------
// The original default accent was a pure neon #00FF41 (sRGB green at max
// saturation). On the near-black #0E0E0E foundation this produced painful
// halation / eye strain during prolonged sessions. We tone it to #00CC66 —
// the same reduced-saturation green used by VS Code's "Dark+" default
// accent — which retains the brand's terminal-green identity while
// dropping peak luminance from ~0.72 to ~0.44.
//
// WCAG 2.1 AA (4.5:1) text-on-surface checks (verified, Aug 2026):
//   textPrimary #E5E2E1 on #0E0E0E            14.98:1  PASS
//   textSecondary #B9CCB2 on #0E0E0E          11.35:1  PASS
//   textMuted #858585 on #0E0E0E               5.23:1  PASS
//   textDisabled #808080 on #0E0E0E            4.89:1  PASS  (was #666 3.36:1 FAIL)
//   accentOn #003D14 on accent #00CC66         5.86:1  PASS
//   accentDim #00B855 on #0E0E0E               7.34:1  PASS
//   light textPrimary #1A1A1A on #FFFFFF       17.40:1  PASS
//   light accentOn #D6F5E3 on #006225          6.50:1  PASS
//   light error #D32F2F on #FFFFFF             4.98:1  PASS
//   light warning #B75800 on #FFFFFF           4.76:1  PASS  (was #ED6C00 3.11:1 FAIL)
//   PurpleNeon accentOn #3A1C54 on #B497BD     5.50:1  PASS
//   Capuchin accentOn #F5F0E8 on #8D5524       5.35:1  PASS  (was #2B1703 2.82:1 FAIL)
//   Sand accentOn #3A1C03 on #D9730F            4.76:1  PASS
// ===========================================================================

namespace {

// Foundation selector — true selects the dark token set, false the light set.
// All other tokens (accent, syntax overrides) are parameterised on top.
struct Foundation
{
    juce::Colour background;
    juce::Colour surface;
    juce::Colour surfaceLow;
    juce::Colour surfaceContainer;
    juce::Colour surfaceHigh;
    juce::Colour surfaceHighest;
    juce::Colour surfaceBright;

    juce::Colour textPrimary;
    juce::Colour textSecondary;
    juce::Colour textMuted;
    juce::Colour textDisabled;

    juce::Colour error;
    juce::Colour warning;

    juce::Colour codeText;
    juce::Colour codeComment;
    juce::Colour codeType;
    juce::Colour codeString;
    juce::Colour codeFunction;
    juce::Colour codeBracket;
    juce::Colour codeLineNum;

    static Foundation dark() noexcept
    {
        return Foundation{
            /* background        */ juce::Colour(0xff0e0e0eu),
            /* surface           */ juce::Colour(0xff131313u),
            /* surfaceLow        */ juce::Colour(0xff1c1b1bu),
            /* surfaceContainer  */ juce::Colour(0xff201f1fu),
            /* surfaceHigh       */ juce::Colour(0xff2a2a2au),
            /* surfaceHighest    */ juce::Colour(0xff353534u),
            /* surfaceBright     */ juce::Colour(0xff3a3939u),

            /* textPrimary       */ juce::Colour(0xffe5e2e1u),
            /* textSecondary     */ juce::Colour(0xffb9ccb2u),
            /* textMuted         */ juce::Colour(0xff858585u),
            /* textDisabled      */ juce::Colour(0xff808080u),  // WCAG AA: 4.89:1 on #0e0e0e

            /* error             */ juce::Colour(0xffff5f56u),
            /* warning           */ juce::Colour(0xffe0a020u),

            /* codeText          */ juce::Colour(0xffd4d4d4u),
            /* codeComment       */ juce::Colour(0xff6a9955u),
            /* codeType          */ juce::Colour(0xff4ec9b0u),
            /* codeString        */ juce::Colour(0xffce9178u),
            /* codeFunction      */ juce::Colour(0xffd4d4d4u),
            /* codeBracket       */ juce::Colour(0xffffd700u),
            /* codeLineNum       */ juce::Colour(0xff858585u),
        };
    }

    static Foundation light() noexcept
    {
        return Foundation{
            /* background        */ juce::Colour(0xffffffffu),
            /* surface           */ juce::Colour(0xfff5f5f5u),
            /* surfaceLow        */ juce::Colour(0xffe8e8e8u),
            /* surfaceContainer  */ juce::Colour(0xffd8d8d8u),
            /* surfaceHigh       */ juce::Colour(0xffc8c8c8u),
            /* surfaceHighest    */ juce::Colour(0xffb8b8b8u),
            /* surfaceBright     */ juce::Colour(0xffa8a8a8u),

            /* textPrimary       */ juce::Colour(0xff1a1a1au),
            /* textSecondary     */ juce::Colour(0xff4a4a4au),
            /* textMuted         */ juce::Colour(0xff7a7a7au),
            /* textDisabled      */ juce::Colour(0xff9a9a9au),

            /* error             */ juce::Colour(0xffd32f2fu),
            /* warning           */ juce::Colour(0xffb75800u),  // WCAG AA: 4.76:1 on #ffffff

            /* codeText          */ juce::Colour(0xff2d2d2du),
            /* codeComment       */ juce::Colour(0xff2e7d32u),
            /* codeType          */ juce::Colour(0xff00796bu),
            /* codeString        */ juce::Colour(0xffe65100u),
            /* codeFunction      */ juce::Colour(0xff5865f5u),
            /* codeBracket       */ juce::Colour(0xff8a6d00u),
            /* codeLineNum       */ juce::Colour(0xff555555u),
        };
    }
};

// Build a complete Palette from a foundation + accent family.
// codeKeyword / codeMacro are optional overrides (defaults are VS Code
// Dark+ colours); all other syntax tokens come from the foundation so
// the dark themes share one code-colour spec sheet.
Palette buildPalette(const Foundation& f,
                      juce::Colour accent,
                      juce::Colour accentDim,
                      juce::Colour accentOn,
                      juce::Colour codeKeyword = juce::Colour(0xff569cd6u),
                      juce::Colour codeMacro   = juce::Colour(0xffc586c0u)) noexcept
{
    return Palette{
        /* background        */ f.background,
        /* surface           */ f.surface,
        /* surfaceLow        */ f.surfaceLow,
        /* surfaceContainer  */ f.surfaceContainer,
        /* surfaceHigh       */ f.surfaceHigh,
        /* surfaceHighest    */ f.surfaceHighest,
        /* surfaceBright     */ f.surfaceBright,

        /* textPrimary       */ f.textPrimary,
        /* textSecondary     */ f.textSecondary,
        /* textMuted         */ f.textMuted,
        /* textDisabled      */ f.textDisabled,

        /* accent            */ accent,
        /* accentDim         */ accentDim,
        /* accentOn          */ accentOn,

        /* error             */ f.error,
        /* warning           */ f.warning,

        /* codeText          */ f.codeText,
        /* codeComment       */ f.codeComment,
        /* codeKeyword       */ codeKeyword,
        /* codeType          */ f.codeType,
        /* codeString        */ f.codeString,
        /* codeFunction      */ f.codeFunction,
        /* codeMacro         */ codeMacro,
        /* codeBracket       */ f.codeBracket,
        /* codeLineNum       */ f.codeLineNum,
    };
}

} // namespace

Palette Palette::defaultPalette() noexcept
{
    // Dark foundation + the toned-down brand-green accent family.
    return buildPalette(
        Foundation::dark(),
        /* accent     */ juce::Colour(0xff00cc66u),
        /* accentDim  */ juce::Colour(0xff00b855u),
        /* accentOn   */ juce::Colour(0xff003d14u));
}

// ===========================================================================
// Constructor — initialises the default palette and applies all colour IDs
// ===========================================================================

HathorLookAndFeel::HathorLookAndFeel()
    : currentPalette_(Palette::defaultPalette())
{
    globalPalette_ = &currentPalette_;
    applyPaletteToColours();
}

// ===========================================================================
// Palette management — runtime switching (A1 design-token engine)
// ===========================================================================

void HathorLookAndFeel::setPalette(const Palette& newPalette)
{
    currentPalette_ = newPalette;
    applyPaletteToColours();

    // Broadcast to every live component. JUCE's sendLookAndFeelChange() recurses
    // into child components, so HathorTab (and any other component that overrides
    // lookAndFeelChanged()) re-applies its palette-derived colours here.
    for (int i = juce::Desktop::getInstance().getNumComponents(); --i >= 0;)
    {
        if (auto* c = juce::Desktop::getInstance().getComponent(i))
            c->sendLookAndFeelChange();
    }
}

// ===========================================================================
// applyPaletteToColours — single place where palette tokens map to JUCE
// colour IDs.  Called from the constructor and setPalette().
// ===========================================================================

void HathorLookAndFeel::applyPaletteToColours() noexcept
{
    const Palette& p = currentPalette_;

    // -----------------------------------------------------------------------
    // Window / component backgrounds
    // -----------------------------------------------------------------------
    setColour(juce::ResizableWindow::backgroundColourId,  p.background);
    setColour(juce::DocumentWindow::backgroundColourId,   p.background);

    // -----------------------------------------------------------------------
    // Generic component / label text
    // -----------------------------------------------------------------------
    setColour(juce::Label::textColourId,       p.textPrimary);
    setColour(juce::Label::backgroundColourId, p.background);

    // -----------------------------------------------------------------------
    // TextEditor (chat input, search bar, etc.)
    // -----------------------------------------------------------------------
    setColour(juce::TextEditor::backgroundColourId,    p.surfaceHigh);
    setColour(juce::TextEditor::textColourId,          p.textPrimary);
    setColour(juce::TextEditor::outlineColourId,       p.surfaceHighest);
    setColour(juce::TextEditor::focusedOutlineColourId, p.accent);
    setColour(juce::TextEditor::highlightColourId,     p.accent.withAlpha(0.4f));
    setColour(juce::TextEditor::highlightedTextColourId, p.background);
    setColour(juce::CaretComponent::caretColourId,     p.accent);

    // -----------------------------------------------------------------------
    // ListBox / TreeView (Explorer panel)
    // -----------------------------------------------------------------------
    setColour(juce::ListBox::backgroundColourId,  p.background);
    setColour(juce::ListBox::outlineColourId,     juce::Colours::transparentBlack);

    setColour(juce::TreeView::backgroundColourId,             p.background);
    setColour(juce::TreeView::linesColourId,                  p.surfaceHighest);
    setColour(juce::TreeView::selectedItemBackgroundColourId, p.surfaceLow);

    // -----------------------------------------------------------------------
    // CodeEditorComponent
    // -----------------------------------------------------------------------
    setColour(juce::CodeEditorComponent::backgroundColourId,  p.surface);
    setColour(juce::CodeEditorComponent::defaultTextColourId, p.codeText);
    setColour(juce::CodeEditorComponent::highlightColourId,   p.accent.withAlpha(0.3f));
    setColour(juce::CodeEditorComponent::lineNumberBackgroundId, p.surfaceLow);
    setColour(juce::CodeEditorComponent::lineNumberTextId,    p.codeLineNum);

    // -----------------------------------------------------------------------
    // TabbedComponent / TabbedButtonBar
    // -----------------------------------------------------------------------
    setColour(juce::TabbedComponent::backgroundColourId,  p.background);
    setColour(juce::TabbedComponent::outlineColourId,    p.surfaceHighest);
    setColour(juce::TabbedButtonBar::tabTextColourId,    p.textSecondary);
    setColour(juce::TabbedButtonBar::tabOutlineColourId, p.surfaceHighest);
    setColour(juce::TabbedButtonBar::frontTextColourId, p.textPrimary);

    // -----------------------------------------------------------------------
    // ScrollBar
    // -----------------------------------------------------------------------
    setColour(juce::ScrollBar::backgroundColourId, juce::Colours::transparentBlack);
    setColour(juce::ScrollBar::thumbColourId,      p.surfaceHighest);
    setColour(juce::ScrollBar::trackColourId,      p.background);

    // -----------------------------------------------------------------------
    // Slider
    // -----------------------------------------------------------------------
    setColour(juce::Slider::backgroundColourId,          p.surfaceHigh);
    setColour(juce::Slider::thumbColourId,               p.textPrimary);
    setColour(juce::Slider::trackColourId,               p.surfaceHighest);
    setColour(juce::Slider::rotarySliderFillColourId,    p.accent);
    setColour(juce::Slider::rotarySliderOutlineColourId, p.surfaceHighest);
    setColour(juce::Slider::textBoxTextColourId,        p.textPrimary);
    setColour(juce::Slider::textBoxBackgroundColourId,  p.surfaceHigh);
    setColour(juce::Slider::textBoxOutlineColourId,     p.surfaceHighest);
    setColour(juce::Slider::textBoxHighlightColourId,   p.accent.withAlpha(0.4f));

    // -----------------------------------------------------------------------
    // ComboBox
    // -----------------------------------------------------------------------
    setColour(juce::ComboBox::backgroundColourId, p.surfaceHigh);
    setColour(juce::ComboBox::textColourId,     p.textPrimary);
    setColour(juce::ComboBox::outlineColourId,  p.surfaceHighest);
    setColour(juce::ComboBox::buttonColourId,   p.surfaceHigh);
    setColour(juce::ComboBox::arrowColourId,    p.textPrimary);

    // -----------------------------------------------------------------------
    // PopupMenu
    // -----------------------------------------------------------------------
    setColour(juce::PopupMenu::backgroundColourId,             p.surfaceContainer);
    setColour(juce::PopupMenu::textColourId,                   p.textPrimary);
    setColour(juce::PopupMenu::highlightedBackgroundColourId,  p.accent.withAlpha(0.3f));
    setColour(juce::PopupMenu::highlightedTextColourId,        p.background);
    setColour(juce::PopupMenu::headerTextColourId,             p.textMuted);

    // -----------------------------------------------------------------------
    // AlertWindow / DialogWindow
    // -----------------------------------------------------------------------
    setColour(juce::AlertWindow::backgroundColourId,  p.surfaceContainer);
    setColour(juce::AlertWindow::textColourId,        p.textPrimary);
    setColour(juce::AlertWindow::outlineColourId,     p.surfaceHighest);

    setColour(juce::DialogWindow::backgroundColourId, p.surfaceContainer);
    setColour(juce::DialogWindow::textColourId,       p.textPrimary);

    // -----------------------------------------------------------------------
    // TextButton
    // -----------------------------------------------------------------------
    setColour(juce::TextButton::buttonColourId,   p.surfaceHigh);
    setColour(juce::TextButton::buttonOnColourId, p.accent);
    setColour(juce::TextButton::textColourOffId,  p.textPrimary);
    setColour(juce::TextButton::textColourOnId,   p.background);

    // -----------------------------------------------------------------------
    // TooltipWindow
    // -----------------------------------------------------------------------
    setColour(juce::TooltipWindow::backgroundColourId, p.surfaceContainer);
    setColour(juce::TooltipWindow::textColourId,       p.textPrimary);
    setColour(juce::TooltipWindow::outlineColourId,    p.surfaceHighest);

    // -----------------------------------------------------------------------
    // PropertyComponent / PropertyPanel
    // -----------------------------------------------------------------------
    setColour(juce::PropertyComponent::backgroundColourId, p.background);
    setColour(juce::PropertyComponent::labelTextColourId,  p.textSecondary);
}

// ===========================================================================
// Theme registry — five themes derived from a single parameterised palette
// builder (Agent 2.2).  Each theme is now: foundation + accent family +
// optional syntax-override pair, with no duplicated literal foundation blocks.
// ===========================================================================

Palette paletteForTheme(ThemeId id) noexcept
{
    switch (id)
    {
        // ---------------------------------------------------------------
        // Dark — default brand-green accent on the dark foundation.
        // See Palette::defaultPalette() / design rationale above.
        // ---------------------------------------------------------------
        case ThemeId::Dark:
            return Palette::defaultPalette();

        // ---------------------------------------------------------------
        // Purple / Neon — dark foundation + purple accent family.
        // Only the keyword/macro syntax tokens are overridden to purple
        // to stay on-theme; everything else is inherited from Foundation::dark().
        // ---------------------------------------------------------------
        case ThemeId::PurpleNeon:
            return buildPalette(
                Foundation::dark(),
                /* accent       */ juce::Colour(0xffb497bdu),
                /* accentDim    */ juce::Colour(0xffa384acu),
                /* accentOn     */ juce::Colour(0xff3a1c54u),
                /* codeKeyword  */ juce::Colour(0xffc678ddu),
                /* codeMacro    */ juce::Colour(0xffc678ddu));

        // ---------------------------------------------------------------
        // Capuchin — dark foundation + warm brown accent family.
        // Accent #8D5524 is a dark brown, so accentOn is a warm cream
        // (#F5F0E8) to provide WCAG AA text contrast (5.35:1).
        // ---------------------------------------------------------------
        case ThemeId::Capuchin:
            return buildPalette(
                Foundation::dark(),
                /* accent       */ juce::Colour(0xff8d5524u),
                /* accentDim    */ juce::Colour(0xff7a4a1du),
                /* accentOn     */ juce::Colour(0xfff5f0e8u));

        // ---------------------------------------------------------------
        // Sand — dark foundation + warm amber accent family.
        // ---------------------------------------------------------------
        case ThemeId::Sand:
            return buildPalette(
                Foundation::dark(),
                /* accent       */ juce::Colour(0xffd9730fu),
                /* accentDim    */ juce::Colour(0xffbd5e0au),
                /* accentOn     */ juce::Colour(0xff3a1c03u));

        // ---------------------------------------------------------------
        // Light — light foundation + forest-green accent family.
        // All syntax tokens come from Foundation::light(); the light
        // warning colour (#B75800) was tuned for 4.76:1 on white.
        // ---------------------------------------------------------------
        case ThemeId::Light:
            return buildPalette(
                Foundation::light(),
                /* accent       */ juce::Colour(0xff006225u),
                /* accentDim    */ juce::Colour(0xff00521cu),
                /* accentOn     */ juce::Colour(0xffd6f5e3u),
                /* codeKeyword  */ juce::Colour(0xff1565c0u),
                /* codeMacro    */ juce::Colour(0xffaa00ffu));
    }

    return Palette::defaultPalette();
}

juce::String themeDisplayName(ThemeId id) noexcept
{
    switch (id)
    {
        case ThemeId::Dark:       return "Dark";
        case ThemeId::PurpleNeon: return "Purple / Neon";
        case ThemeId::Capuchin:   return "Capuchin";
        case ThemeId::Sand:       return "Sand";
        case ThemeId::Light:      return "Light";
    }
    return "Dark";
}

const Palette* HathorLookAndFeel::globalPalette_ = nullptr;

// ===========================================================================
// getTypefaceForFont — NOT overridden.
//
// The previous override hijacked ALL font requests (including sans-serif UI
// chrome) to JetBrains Mono.  Per Audit §1.2 I6 the global hijack is removed:
// JetBrains Mono is used only where code is displayed (via getCodeFont()),
// and Inter (embedded, OFL) is used for all other UI via getUiFont().
// JUCE's default typeface resolution is allowed to handle fallback for any
// component that neither calls getUiFont() nor getCodeFont().
// ===========================================================================

// ===========================================================================
// getTextButtonFont — Inter Medium at ~55% of button height for UI labels
// ===========================================================================

// ===========================================================================
// getTextButtonFont — JetBrains Mono Bold for text buttons
// ===========================================================================

juce::Font HathorLookAndFeel::getTextButtonFont(juce::TextButton& /*button*/,
                                                 int buttonHeight)
{
    // Use Medium weight at ~55% of button height for label-sized text.
    // Inter (proportional UI font) — not JetBrains Mono.
    const float h = static_cast<float>(buttonHeight) * 0.55f;
    return HathorLookAndFeel::uiFontMedium(juce::jmax(h, 10.0f));
}

// ===========================================================================
// drawButtonBackground — dark theme button with green accent
// ===========================================================================

void HathorLookAndFeel::drawButtonBackground(juce::Graphics& g,
                                              juce::Button& button,
                                              const juce::Colour& /*backgroundColour*/,
                                              bool shouldDrawButtonAsHighlighted,
                                              bool shouldDrawButtonAsDown)
{
    const Palette& p = currentPalette_;

    const juce::Rectangle<float> bounds = button.getLocalBounds().toFloat();

    juce::Colour bg;

    if (button.getToggleState())
        bg = p.accent;                                // active = green
    else if (shouldDrawButtonAsDown)
        bg = p.surfaceContainer;                     // pressed = slightly lighter
    else if (shouldDrawButtonAsHighlighted)
        bg = p.surfaceLow;                           // hover = subtle tint
    else
        bg = p.surfaceHigh;                          // default

    g.setColour(bg);
    g.fillRoundedRectangle(bounds, HathorLookAndFeel::Radius::small);
}

// ===========================================================================
// drawButtonText — green on active, primary text on inactive
// ===========================================================================

void HathorLookAndFeel::drawButtonText(juce::Graphics& g,
                                       juce::TextButton& button,
                                       bool shouldDrawButtonAsHighlighted,
                                       bool shouldDrawButtonAsDown)
{
    const Palette& p = currentPalette_;

    juce::Colour textCol = p.textPrimary;

    if (button.getToggleState())
        textCol = p.background; // green bg + dark text when on

    // Get the button's font via the LookAndFeel hook (Inter UI font).
    juce::Font font = getTextButtonFont(button, button.getHeight());

    if (shouldDrawButtonAsHighlighted || shouldDrawButtonAsDown)
        font = HathorLookAndFeel::uiFontBold(font.getHeight());
    else
        font = HathorLookAndFeel::uiFontRegular(font.getHeight());

    g.setColour(textCol);
    g.setFont(font);

    const juce::Rectangle<int> bounds = button.getLocalBounds();
    g.drawFittedText(button.getButtonText(), bounds,
                     juce::Justification::centred, 1, 1.0f);
}

// ===========================================================================
// drawLinearSlider — pill-track aesthetic from the mockup
// ===========================================================================

void HathorLookAndFeel::drawLinearSlider(juce::Graphics& g,
                                          int x, int y, int width, int height,
                                          float sliderPos,
                                          float /*minSliderPos*/, float /*maxSliderPos*/,
                                          juce::Slider::SliderStyle /*style*/,
                                          juce::Slider& /*slider*/)
{
    const Palette& p = currentPalette_;

    const bool isHorizontal = (width > height);
    const int  thumbSize    = isHorizontal ? 12 : 12;
    const float trackH       = isHorizontal ? 4.0f : static_cast<float>(width);

    const float trackY = y + (height - trackH) / 2.0f;
    juce::Rectangle<float> trackRect(x, trackY, width, trackH);

    // Track background (pill shape)
    g.setColour(p.surfaceHighest);
    g.fillRoundedRectangle(trackRect, trackH / 2.0f);

    // Filled portion
    const float fillW = juce::jlimit(0.0f, static_cast<float>(width), sliderPos - x);
    if (fillW > 0)
    {
        juce::Rectangle<float> fillRect(x, trackY, fillW, trackH);
        g.setColour(p.accent);
        g.fillRoundedRectangle(fillRect, trackH / 2.0f);
    }

    // Thumb (circle)
    const float thumbX = juce::jlimit(static_cast<float>(x),
                                       static_cast<float>(x + width),
                                       sliderPos);
    const float thumbY = y + height / 2.0f;
    g.setColour(p.textPrimary);
    g.fillEllipse(thumbX - thumbSize / 2.0f,
                  thumbY - thumbSize / 2.0f,
                  thumbSize, thumbSize);
}

// ===========================================================================
// drawScrollbar — thin thumb, transparent track
// ===========================================================================

void HathorLookAndFeel::drawScrollbar(juce::Graphics& g,
                                       juce::ScrollBar& /*scrollbar*/,
                                       int x, int y, int width, int height,
                                       bool /*isScrollbarVertical*/,
                                       int /*thumbStartPosition*/, int /*thumbSize*/,
                                       bool /*isMouseOver*/, bool /*isMouseDown*/)
{
    const Palette& p = currentPalette_;

    // Track is transparent — let the parent background show through.
    // Thumb: dim, 8 px wide, 4 px corner radius (matches mockup).
    g.setColour(p.surfaceHighest);

    juce::Rectangle<float> thumb(x, y, width, height);
    g.fillRoundedRectangle(thumb, HathorLookAndFeel::Radius::small);
}
